### ISSUE TITLE
Error 'enoent' during handoffs

### ISSUE THREAD

**Issue by starstuck** [outlyerapp/dalmatinerdb#24] opened 2016-02-18 17:49 UTC
Crasher report

```
initial call: riak_core_vnode_worker:init/1
registered_name: []
exception exit: {{{badmatch,{error,enoent}},
                 [{metric_io,bucket_fold_fun,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,248}]},
                  {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
                  {metric_io,'-fold_byckets_fun/4-fun-1-',3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,266}]},
                  {metric_worker,handle_work,3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_worker.erl"},{line,22}]},
                  {riak_core_vnode_worker,handle_cast,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/default/lib/riak_core/src/riak_core_vnode_worker.erl"},{line,68}]},
                  {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
                  {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},
                  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},
                [{gen_server,terminate,7,[{file,"gen_server.erl"},{line,826}]},
                 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
ancestors: [<0.25250.0>,<0.25249.0>,<0.25248.0>,<0.25246.0>,riak_core_vnode_sup,riak_core_sup,<0.128.0>]
messages: []
dictionary: [{is_visit_item_timer_set,true}]
```

**Comment by davecromberge** [comment] 2016-02-29 14:35
Also happens during write operations:
```
2016-02-29 14:32:19 =ERROR REPORT====
** Generic server <0.26622.46> terminating
** Last message in was {'$gen_cast',{work,{fold,#Fun<metric_io.1.55205490>,#Fun<metric_vnode.2.56692890>},{server,undefined,{<0.24370.52>,#Ref<0.0.29360132.146612>}},<0.16098.20>}}
** When Server state == {state,metric_worker,{state,796404212529925613630523570952818286101572616192}}
** Reason for termination ==
** {{badmatch,{error,enoent}},[{metric_io,bucket_fold_fun,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,248}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{metric_io,'-fold_byckets_fun/4-fun-1-',3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,266}]},{metric_worker,handle_work,3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_worker.erl"},{line,22}]},{riak_core_vnode_worker,handle_cast,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/default/lib/riak_core/src/riak_core_vnode_worker.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2016-02-29 14:32:19 =CRASH REPORT====
  crasher:
    initial call: riak_core_vnode_worker:init/1
    pid: <0.26622.46>
    registered_name: []
    exception exit: {{{badmatch,{error,enoent}},[{metric_io,bucket_fold_fun,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,248}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{metric_io,'-fold_byckets_fun/4-fun-1-',3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,266}]},{metric_worker,handle_work,3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_worker.erl"},{line,22}]},{riak_core_vnode_worker,handle_cast,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/default/lib/riak_core/src/riak_core_vnode_worker.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,826}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.16101.20>,<0.16100.20>,<0.16098.20>,<0.16096.20>,riak_core_vnode_sup,riak_core_sup,<0.126.0>]
    messages: []
    links: [<0.16100.20>,<0.16101.20>,<0.121.0>]
    dictionary: [{is_visit_item_timer_set,true}]
    trap_exit: false
    status: running
    heap_size: 28690
    stack_size: 27
    reductions: 214832763
  neighbours:
2016-02-29 14:32:19 =SUPERVISOR REPORT====
     Supervisor: {<0.16101.20>,poolboy_sup}
     Context:    child_terminated
     Reason:     {{badmatch,{error,enoent}},[{metric_io,bucket_fold_fun,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,248}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{metric_io,'-fold_byckets_fun/4-fun-1-',3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_io.erl"},{line,266}]},{metric_worker,handle_work,3,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/deb/lib/metric_vnode/src/metric_worker.erl"},{line,22}]},{riak_core_vnode_worker,handle_cast,2,[{file,"/data/jenkins/workspace/dalmatinerdb/_build/default/lib/riak_core/src/riak_core_vnode_worker.erl"},{line,68}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
     Offender:   [{pid,<0.26622.46>},{id,riak_core_vnode_worker},{mfargs,{riak_core_vnode_worker,start_link,undefined}},{restart_type,temporary},{shutdown,5000},{child_type,worker}]
```

**Comment by davecromberge** [comment] 2016-03-03 12:15
Upon further investigation, this seems to occur when a bucket dir is missing an mstore file.  

For example, on ddb node 2, the mstore is missing in the following directory:

```
Partition: 565190086311560112899081243902000074007567663104
Bucket:   0b5e90e2-7d40-4753-85f9-19545018e9ca
```

**Comment by davecromberge** [comment] 2016-03-04 10:47
The cause would be that the metric index file could not be created in the first place, due to possibly exceeding the allowable limit on open file handles. Once the limit was adjusted, the node needs to be restarted. This clears the in-memory cache of mstores, and forces mstores to be re-initialised, and in so doing repair the indices.

**Comment by davecromberge** [comment] 2016-03-04 11:53
Unfortunately this issue recurred after about half an hour, I closed it too hastily.
The store is only initialised properly on construction.  Handoffs make the assumption that the store is available in each bucket, and do not follow the normal store construction process - if not, the entire handoff process fails.

**Comment by davecromberge** [comment] 2016-03-11 14:50
This has not re-occured due to raising file limits and ensuring files are properly repaired.

**Closed as completed by davecromberge** 2016-03-11 14:50 UTC
Labels: bug
